multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: debug

blocks_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync

alertmanager_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-alerts
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true

compactor:
  data_dir: /tmp/mimir/compactor

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

memberlist:
  join_members:
    - mimir:7946
  bind_port: 7946